name: Test
on: [push]

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.13.1
    - name: install
      run: npm ci
    - name: test
      run: npm run test
